- job_name: 'kubernetes-http-services'
  metrics_path: /probe
  params:
    module: [http_2xx]  # 使用定义的http模块
  kubernetes_sd_configs:
  - role: service  # service 类型的服务发现
  relabel_configs:
  # 只有service的annotation中配置了 prometheus.io/http_probe=true 的才进行发现
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_http_probe]
    action: keep
    regex: true
  - source_labels: [__address__]
    target_label: __param_target
  - target_label: __address__
    replacement: blackbox:9115  #blackbox-exporter访问地址
  - source_labels: [__param_target]
    target_label: instance
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_service_name]
    target_label: kubernetes_name

- job_name: 'kubernetes-ingresses'
  metrics_path: /probe
  params:
    module: [http_2xx]  # 使用定义的http模块
  kubernetes_sd_configs:
  - role: ingress  # ingress 类型的服务发现
  relabel_configs:
  # 只有ingress的annotation中配置了 prometheus.io/http_probe=true的才进行发现
  - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_http_probe]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]
    regex: (.+);(.+);(.+)
    replacement: ${1}://${2}${3}
    target_label: __param_target
  - target_label: __address__
    replacement: blackbox:9115
  - source_labels: [__param_target]
    target_label: instance
  - action: labelmap
    regex: __meta_kubernetes_ingress_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_ingress_name]
    target_label: kubernetes_name

- job_name: 'blackbox_http_2xx'
  scrape_interval: 45s
  metrics_path: /probe
  params:
    module: [http_2xx]  # Look for a HTTP 200 response.
  static_configs:
    - targets:
      - https://oppc.rencaiyoujia.com/ping
      - https://www.rencaiyoujia.com
      - https://m.rencaiyoujia.com
      - https://www.m.rencaiyoujia.com
      - https://fa.rencaiyoujia.com
      - https://rencaiyoujia.com
      - https://rcpgadmin.rencaiyoujia.com
      - https://dsfh5.rencaiyoujia.com
      - http://pubapi.rencaiyoujia.com/ping
      - https://assessh5.rencaiyoujia.com
      - https://ommp.rencaiyoujia.com
      - https://ommp.rencaiyoujia.com
      - https://risk-rule.rencaiyoujia.com/ping
      - https://bcpay-ad-api.rencaiyoujia.com/ping
      - https://bcpay-api.rencaiyoujia.com/ping
      - https://walletapi.rencaiyoujia.com/ping
      - https://risk-frontend.rencaiyoujia.com
      - https://withdraw.rencaiyoujia.com
      - https://wallet.rencaiyoujia.com
      - https://nacos.rencaiyoujia.com/nacos
      - https://s.rencaiyoujia.com
      - https://www.xiaocaiyoujia.com
      - https://www.xiaocaiyoujia.com/h5/
      - https://www.m.govjob.rencaiyoujia.com/
      - https://www.rencaiyoujia.com/govapi/test/ping
      - https://govjob.rencaiyoujia.com/auth
      - https://govjobadmin.rencaiyoujia.com/
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
