{
 "title": "ccwork-dashboard",
 "time": { "from": "2022-06-23T03:00:00.000Z", "to": "2022-06-23T03:20:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pod CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\"}[5m])"
    }
   ]
  },
  {
   "title": "pod网络",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])",
     "legendFormat": "入口-[$namespace]-$pod"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])",
     "legendFormat": "出口-[$namespace]-$pod"
    }
   ]
  },
  {
   "title": "pod内存",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"${namespace}\",pod=\"${pod}\", container!=\"POD\"}"
    }
   ]
  }
 ]
}