apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-prometheus
    release: prometheus-operator  #【必须】prometheus用来选择servicemonitor
  name: prometheus-operator-prometheus
  namespace: cattle-prometheus
spec:
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - cattle-prometheus
  selector:
    matchLabels:
      app: mysqld-exporter