apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    app: prometheus-operator-kube-etcd
    release: prometheus-operator
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 2381
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    app: prometheus-operator-kube-etcd
    release: prometheus-operator
subsets:
- addresses:
  - ip: 172.22.22.7
    nodeName: k8s-master01
  - ip: 172.22.22.8
    nodeName: k8s-master02
  - ip: 172.22.22.9
    nodeName: k8s-master03
  ports:
  - name: http-metrics
    port: 2381
    protocol: TCP
