apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: cattle-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:    
      - name: mysqld-exporter
        image: prom/mysqld-exporter
        imagePullPolicy: IfNotPresent
        env:
        - name: DATA_SOURCE_NAME
          value: exporter:rcyj1qaz2wsx@(10.15.9.210:3306)/
          # CREATE USER 'exporter'@'172.22.22.%' IDENTIFIED BY 'rcyj1qaz2wsx' WITH MAX_USER_CONNECTIONS 3;
          # GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'172.22.22.%';  
          # CREATE USER 'exporter'@'10.15.9.%' IDENTIFIED BY 'rcyj1qaz2wsx' WITH MAX_USER_CONNECTIONS 3;
          # GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'10.15.9.%';    
        ports:
        - containerPort: 9104
          protocol: TCP
          name: metrics
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /rcyj-platformB
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 35
        #   periodSeconds: 5
        #   successThreshold: 1
        #   timeoutSeconds: 2          
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /rcyj-platformB
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 35
        #   periodSeconds: 5
        #   successThreshold: 1
        #   timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: mysqld-exporter
  name: mysqld-exporter
  namespace: cattle-prometheus
spec:
  ports:
  - port: 9104
    protocol: TCP
    targetPort: 9104
    name: metrics
  selector:
    app: mysqld-exporter
  sessionAffinity: None
  type: ClusterIP